export const MODALS = {
  USER: {
    PARAM_NAME: "user",
    CHILDREN: {
      VIEW: "view",
      EDIT: "edit",
      DELETE: "delete",
      CREATE: "create",
    },
  },
  AUTH: {
    PARAM_NAME: "auth",
    CHILDREN: {
      LOGOUT: "logout",
    },
  },
  ROLE: {
    PARAM_NAME: "role",
    CHILDREN: {
      EDIT: "edit",
      CREATE: "create",
      DELETE: "delete",
      TOGGLE: "toggle-status",
      ASSIGN_USER: "assign-user",
      REASSIGN_ADMINS: "reassign-admins",
      EDIT_PERMISSIONS: "edit-permissions",
      SELECT_PERMISSIONS: "select-permissions",
      REASSIGN_ADMINS_PROMPT: "reassign-admins-prompt",
    },
  },
  SAVINGS: {
    PARAM_NAME: "savings",
    CHILDREN: {
      UPDATE: "update",
      UPDATE_GROUP: "update-group",
      ACTIVATE: "activate",
      DEACTIVATE: "deactivate",
      UPDATE_INTEREST_RATE: "update-interest-rate",
      ACTIVATE_INTEREST_RATE: "activate-interest-rate",
      DEACTIVATE_INTEREST_RATE: "deactivate-interest-rate",
      VIEW_SAVINGS_DETAILS: "view-savings-details",
    },
  },
  ADMIN: {
    PARAM_NAME: "admin",
    CHILDREN: {
      EDIT_ADMIN_ROLE: "edit-admin-role",
      VIEW: "view",
      EDIT: "edit",
      CREATE: "invite",
      DELETE: "delete",
      ARCHIVE: "archive",
      RESTORE: "restore",
      TOGGLE_STATUS: "toggle-status",
      RESEND_INVITE: "resend-invite",
      BULK_INVITE: "bulk-invite",
      BULK_INVITE_PREVIEW: "bulk-invite-preview",
    },
  },
  CUSTOMER: {
    PARAM_NAME: "customer",
    CHILDREN: {
      VIEW: "view",
      DEACTIVATE: "deactivate",
      ACTIVATE: "activate",
      FREEZE: "freeze-wallet",
      UNFREEZE: "unfreeze-wallet",
      DELETE: "delete",
      ARCHIVE: "archive",
      RESTORE: "restore",
      CREATE: "create",
      UPDATE: "update",
      CUSTOMER_GUARANTOR: "customer-guarantor",
      AGENT_GUARANTOR: "agent-guarantor",
      MERCHANT_BUSINESS_INFORMATION: "merchant-business-information",
      AGENT_BUSINESS_INFORMATION: "agent-business-information",
    },
  },
  TRANSACTION: {
    PARAM_NAME: "transaction",
    CHILDREN: {
      VIEW: "view",
      VIEW_RECENT_ACTIVITY: "view-recent-activity",
    },
  },
  KYC: {
    PARAM_NAME: "kyc-management",
    CHILDREN: {
      VIEW_INDIVIDUAL: "individual-kyc-view",
      VIEW_AGENT: "agent-kyc-view",
      VIEW_MERCHANT: "merchant-kyc-view",
      VIEW_KYC_DOCUMENT: "view-kyc-document",
      APPROVE_INDIVIDUAL_KYC: "approve-individual-kyc",
      APPROVE_AGENT_KYC: "approve-agent-kyc",
      APPROVE_MERCHANT_KYC: "approve-merchant-kyc",
      REJECT_INDIVIDUAL_KYC: "reject-individual-kyc",
      REJECT_AGENT_KYC: "reject-agent-kyc",
      REJECT_MERCHANT_KYC: "reject-merchant-kyc",
      APPROVE_DAILY_LIMIT: "approve-daily-limit",
      REJECT_DAILY_LIMIT: "reject-daily-limit",
    },
  },
  RECOMMENDATION: {
    PARAM_NAME: "recommendation",
    CHILDREN: {
      VIEW: "view",
      EDIT: "edit",
      DELETE: "delete",
    },
  },
  ALARM: {
    PARAM_NAME: "alarm",
    CHILDREN: {
      VIEW: "view",
      EDIT: "edit",
      DELETE: "delete",
      CREATE: "create",
    },
  },
  SAMPLE: {
    PARAM_NAME: "sample",
    CHILDREN: {
      VIEW: "view",
      EDIT: "edit",
      DELETE: "delete",
    },
  },
};
