"use client";

import React from "react";

import type { IconNames } from "@/types";
import { cn } from "@/libs";
import { toKebabCase } from "@/utils";

type Props = React.ComponentProps<"svg"> &
  Readonly<{ className?: string; name: IconNames }>;

// Icon registry - maps icon names to their SVG component imports
// Import icons statically here as they are added to the icons folder
// Example:
// import ArrowDownRightIcon from "../../../public/assets/icons/arrow-down-right.svg";
// Then add: ArrowDownRight: ArrowDownRightIcon,

// TODO: This can be auto-generated by the update-icons script
const iconMap: Partial<
  Record<IconNames, React.ComponentType<React.SVGProps<SVGSVGElement>>>
> = {
  // Add icon imports here as they become available
  // ArrowDownRight: ArrowDownRightIcon,
};

export function CustomIcon({ className, name, ...otherProps }: Props) {
  const Icon = iconMap[name];

  if (!Icon) {
    // Icon not found in registry - return null in production, log warning in development
    if (process.env.NODE_ENV === "development") {
      console.warn(
        `Icon "${name}" not found in iconMap. Please import it in CustomIcon.tsx and add it to the iconMap. Expected file: /public/assets/icons/${toKebabCase(
          name
        )}.svg`
      );
    }
    return null;
  }

  return (
    <span className={cn(className)} data-testid={`icon-${name}`}>
      <Icon {...otherProps} />
    </span>
  );
}
